### ISSUE TITLE
指定地区为日本无法获取到云服务器

### ISSUE THREAD

**Issue by MgArcher** [rockswang/alispot#10]
日志提示：
{"name":"alispot","hostname":"DESKTOP-IA9P0NV","pid":16140,"level":60,"err":{"message":"The resource is out of stock in the specified zone. Please try other types, or choose other regions and zones., URL: https://ecs.ap-northeast-1.aliyuncs.com/","name":"OperationDenied.NoStockError","stack":"OperationDenied.NoStockError: The resource is out of stock in the specified zone. Please try other types, or choose other regions and zones., URL: https://ecs.ap-northeast-1.aliyuncs.com/\n    at httpx.request.then.then (C:\\ShadowsocksR-4.7.0-win\\node_modules\\@alicloud\\pop-core\\lib\\rpc.js:205:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","code":"OperationDenied.NoStock"},"msg":"The resource is out of stock in the specified zone. Please try other types, or choose other regions and zones., URL: https://ecs.ap-northeast-1.aliyuncs.com/","time":"2020-10-29T05:55:02.995Z","v":0}

**Comment by rockswang** [comment]
那个1核1G的实例不是在所有地区节点都有的，不过我看最近上线了一种新的1核1G机型，也可能当地有，你可以手动登阿里云后台看下该地域是否有其它合适的实例类型ID，然后修改config.json的以下字段
```"InstanceType": "ecs.xn4.small"```

**Comment by MgArcher** [comment]
确实是没有那种类型的机器了，所以我修改了"InstanceType": "ecs.xn4.small"为"InstanceType": "ecs.t5-c1m1.large"阿里云显示有的，
但是出现{"name":"alispot","hostname":"DESKTOP-IA9P0NV","pid":12056,"level":60,"err":{"message":"Specified CIDR block overlapped with other subnets., URL: https://ecs.ap-northeast-1.aliyuncs.com/","name":"InvalidCidrBlock.OverlappedError","stack":"InvalidCidrBlock.OverlappedError: Specified CIDR block overlapped with other subnets., URL: https://ecs.ap-northeast-1.aliyuncs.com/\n    at httpx.request.then.then (C:\\ShadowsocksR-4.7.0-win\\node_modules\\@alicloud\\pop-core\\lib\\rpc.js:205:19)\n    at process._tickCallback (internal/process/next_tick.js:68:7)","code":"InvalidCidrBlock.Overlapped"},"msg":"Specified CIDR block overlapped with other subnets., URL: https://ecs.ap-northeast-1.aliyuncs.com/","time":"2020-10-29T06:28:35.007Z","v":0}

**Comment by rockswang** [comment]
这个我还真没见到过，可能是重复调用CreateVpc了，你可以登上去把脚本创建的VPC和安全组都删掉，再试试

**Comment by MgArcher** [comment]
你说的是对的， 现在已经可以成功启动了
