### ISSUE TITLE
代理失效问题

### ISSUE THREAD

**Issue by MgArcher** [rockswang/alispot#7]
请问一下偶尔出现开启代理后可以使用， 但是在使用一段时间后就无法使用，但是过段时间可能又好了这种情况。是因为什么？

**Comment by rockswang** [comment]
敏感地区，敏感时期可能会被GFW封的很快，不过就我的经验，大部分情况只封端口，不封ip，可以ping一下服务器ip，如果还是通的，就ssh登上去换个相邻的端口重启酸酸乳即可，命令行如下：
```shell
nohup python shadowsocksr/shadowsocks/server.py -p 端口 -k 酸酸乳密码 -m aes-128-ctr -O auth_sha1_v4 -o plain >> /dev/null 2>&1 &
```
目前的脚本设置文件中默认开启的安全组端口是33330~33339，换一个这个范围内的即可，否则需要修改安全组规则

**Comment by MgArcher** [comment]
感谢解惑！
